pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                sh '''
                java -version
                node -v
                npm -v
                '''
            }
        }

        stage('Install Appium') {
            steps {
                sh '''
                npm install -g appium
                appium -v
                '''
            }
        }

        stage('Start Appium Server') {
            steps {
                sh '''
                appium --log appium.log &
                sleep 10
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                mvn clean test
                '''
            }
        }
    }

    post {
        always {
            sh 'pkill -f appium || true'
            archiveArtifacts artifacts: '**/target/surefire-reports/*'
        }
    }
}
