pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Sanity') {
            steps {
                echo 'Jenkinsfile parsed successfully'
            }
        }
    }
}
